apiVersion: v1
kind: Secret
metadata:
  name: {{ template "strapi.fullname" . }}
  labels:
    app: {{ template "strapi.name" . }}
    chart: {{ template "strapi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  db-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}