apiVersion: v2
name: strapi
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 3.0.1
dependencies:
- name: "postgresql"
  version: "8.10.5"
  repository: "https://charts.bitnami.com/bitnami"
